version: 2.1

orbs:
  node: circleci/node@5.1.0
  ruby: circleci/ruby@2.1.2
  aws-cli: circleci/aws-cli@3.1.5

jobs:           
  # iOS Build
  ios:
    macos:
      xcode: 15.0.1
    steps:
      - checkout
      - run:
          command: ls -lah
#************************************************************************************************
      # Node modules with caching 
      - node/install:
          node-version: '20.9.0' 
      # - ruby/install:
      #     version: '2.7.5'
      #cococapods install (3.0.5) after ruby 
      - run:
          name: check v
          command: |
            node -v
            ruby -v
      - run:
          name: Install bundle dependencies
          command: |
            gem uninstall activesupport --all --executables --ignore-dependencies
            gem install activesupport --version 7.0.8
            bundle install --full-index

            
      # Installing Fastlane
      - run:
          name: install fastlane 
          command: gem install fastlane 
      - run: 
          name: node modules check
          command: |
            npm install
            ls -l

      - run: 
          name: pod install
          command: |
            cd ios && pod install
            
      # - run:
      #     name: initial fastlane 
      #     command: |
      #       bundle update --bundler
      #       cd ios && bundle exec fastlane init
      #       ls -l

        
      - run:
          name: Build and test
          command: |
            fastlane custom_lane

#******************************************************************************************
      # - run: 
      #     name: create apk
      #     command: aws s3 cp ios/build/outputs/apk/debug/app-debug.apk s3://my-bucket-name/app-debug.apk
          


workflows:
  build_and_test:
    jobs:
      - ios
