version: 2.1

orbs:
  node: circleci/node@5.1.0
  ruby: circleci/ruby@2.0.0
  aws-cli: circleci/aws-cli@3.1.5

jobs:           
  # iOS Build
  ios:
    macos:
      xcode: 14.2
    steps:
      - checkout
      - run:
          command: ls -lah
# installng fastlane 
      - ruby/install:
          version: '2.7.5' 
      - run:
          command: ruby --version
workflows:
  build_and_test:
    jobs:
      - ios
