platform :ios do
    desc "IOS Build"
    lane :custom_lane do
        puts "Hello from custom lane"
    end
    lane :Build_process do
        create_keychain(
        name: "build.keychain-db",
        password: "Sp@311200",
        unlock: true,
        default_keychain: true,
        timeout: 3600
        )
        # Import certificate manually (Replace with your actual .p12 file path)
        import_certificate(
            certificate_path: "Certificates.p12",
            certificate_password: "Abcd@1234",
            keychain_name: "build.keychain",
            keychain_password: "Sp@311200"
        )

        app_store_connect_api_key(
            key_id: "57PL28L2UY",
            issuer_id: "589f2d4b-6604-4614-9d4c-f35a64052cad",
            key_content:
            "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgNCWIGJekT4bZ93Ml\nkO0xx66W/GMYslMB9FNVVv0Rr4GgCgYIKoZIzj0DAQehRANCAARmW0Ffjma3Zztc\nAdjkDyAqFQNb1jMxh4o6uP0GirNjILB9ITfbKqHBnc13arvq8Hy8mQDT8nr8zHQy\nP+Hm6lVi\n-----END PRIVATE"
            # key_filepath: "./fastlane/AuthKey_57PL28L2UY.p8" , # base64 encoded key
            is_key_content_base64: true,
            in_house: false # detecting this via ASC private key not currently supported
        )

        # Use the correct provisioning profile manually
        sigh(
            app_identifier: "com.nnn.unity.app",
            provisioning_name: "match_comnnnunityapp.mobileprovision",
            team_id: "26NU4Q2GJC"
        )
        
    end
    desc "Export app"
    lane :build do
        gym(
            project: "unityBlog.xcworkspace",
            scheme: "unityBlog",
            configuration: "Release",
            clean: true,
            export_xcargs: "-allowProvisioningUpdates",
            output_name: "ReleaseApp.ipa"
        )
    end
end