platform :ios do
    desc "IOS Build"
    lane :custom_lane do
        puts "Hello from custom lane"
    end
    # lane : load_asc_api_key do
    #     app_store_connect_api_key(
    #         key_id: "57PL28L2UY",
    #         issuer_id: "589f2d4b-6604-4614-9d4c-f35a64052cad",
    #         key_content: "ABC123" // base64 encoded key,
    #         is_key_content_base64: true,
    #         in_house: false #boolean value if team is Enterprise or not
    #     )
    # end
    desc "Export app"
    lane :build do
        gym(
            project: "unityBlog.xcodeproj",
            scheme: "unityBlog",
            clean: true,
            export_xcargs: "-allowProvisioningUpdates",
            output_name: "ReleaseApp.ipa",
            
        )
    end
end